# Inner Makefile (MousePaw Media Build System)
# Version: 3.2.1

# CHANGE: Project name
NAME = "SIMPLEXpress (Static Library)"

# CHANGE: Set to 'lib' or 'bin'
BUILD_DIR = lib

# Includes inner makefile logic. (Change if necessary to point to inner.mk)
include ../build_system/inner.mk
